const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");
const csv = require("csv-parser");

const db = require("../config/db");

// Project root
const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

// Python AI script
const AI_SCRIPT = path.join(PROJECT_ROOT, "detect.py");

// Detection CSV generated by Python
const CSV_FILE = path.join(
    PROJECT_ROOT,
    "output",
    "detection_logs.csv"
);


// ========================================
// RUN AI DETECTION
// ========================================
exports.runDetection = (req, res) => {

    const cameraId = req.body.camera_id;

    if (!cameraId) {
        return res.status(400).json({
            success: false,
            message: "camera_id is required"
        });
    }

    // Check camera exists
    const cameraQuery = `
        SELECT id, name, source, type, status
        FROM cameras
        WHERE id = ?
    `;

    db.query(cameraQuery, [cameraId], (err, cameras) => {

        if (err) {
            console.error("Camera lookup error:", err);

            return res.status(500).json({
                success: false,
                message: "Database error"
            });
        }

        if (cameras.length === 0) {
            return res.status(404).json({
                success: false,
                message: "Camera not found"
            });
        }

        const camera = cameras[0];

        console.log("Starting VisionEdge AI Detection...");
        console.log("Camera:", camera.name);
        console.log("Source:", camera.source);

        // Run Python AI module
        const PYTHON_PATH =
    "C:\\Users\\harsh\\AppData\\Local\\Programs\\Python\\Python310\\python.exe";

const pythonProcess = spawn(
    PYTHON_PATH,
    [AI_SCRIPT],
    {
        cwd: PROJECT_ROOT
    }
);

        let pythonOutput = "";
        let pythonError = "";

        pythonProcess.stdout.on("data", (data) => {

            const output = data.toString();

            pythonOutput += output;

            console.log("[AI]", output.trim());
        });

        pythonProcess.stderr.on("data", (data) => {

            const error = data.toString();

            pythonError += error;

            console.error("[AI ERROR]", error.trim());
        });

        pythonProcess.on("error", (error) => {

            console.error("Python process error:", error);

            return res.status(500).json({
                success: false,
                message: "Unable to start Python AI module",
                error: error.message
            });
        });

        pythonProcess.on("close", (code) => {

            if (code !== 0) {

                return res.status(500).json({
                    success: false,
                    message: "AI detection failed",
                    exit_code: code,
                    error: pythonError
                });
            }

            console.log("AI Detection completed.");

            // Check CSV
            if (!fs.existsSync(CSV_FILE)) {

                return res.status(500).json({
                    success: false,
                    message: "Detection CSV was not generated"
                });
            }

            // Read detection CSV
            const detections = [];

            fs.createReadStream(CSV_FILE)
                .pipe(csv())
                .on("data", (row) => {

                    detections.push(row);

                })
                .on("end", () => {

                    if (detections.length === 0) {

                        return res.status(200).json({
                            success: true,
                            message: "Detection completed but no objects were detected",
                            camera: camera.name,
                            detections: []
                        });
                    }

                    // Insert detections into MySQL
                    const insertQuery = `
                        INSERT INTO detection_logs
                        (
                            camera_id,
                            object_name,
                            confidence,
                            timestamp
                        )
                        VALUES (?, ?, ?, ?)
                    `;

                    let inserted = 0;

                    detections.forEach((detection) => {

                        const objectName = detection.Object;

                        const confidence = parseFloat(
                            detection.Confidence
                        );

                        const timestamp = detection.Timestamp;

                        if (
                            !objectName ||
                            isNaN(confidence)
                        ) {
                            return;
                        }

                        db.query(
                            insertQuery,
                            [
                                camera.id,
                                objectName,
                                confidence,
                                timestamp
                            ],
                            (err) => {

                                if (err) {
                                    console.error(
                                        "Detection insert error:",
                                        err
                                    );

                                    return;
                                }

                                inserted++;

                            }
                        );

                    });

                    // Mark camera active
                    db.query(
                        `
                        UPDATE cameras
                        SET status = 'active'
                        WHERE id = ?
                        `,
                        [camera.id]
                    );

                    res.status(200).json({

                        success: true,

                        message: "AI detection completed successfully",

                        camera: {
                            id: camera.id,
                            name: camera.name
                        },

                        detections_found: detections.length,

                        database_records: inserted,

                        output_video:
                            "output/output.mp4",

                        detection_log:
                            "output/detection_logs.csv"

                    });

                })
                .on("error", (error) => {

                    console.error(
                        "CSV reading error:",
                        error
                    );

                    res.status(500).json({

                        success: false,

                        message:
                            "Failed to read detection results"

                    });

                });
        });
    });
};


// ========================================
// GET DETECTION LOGS
// ========================================
exports.getLogs = (req, res) => {

    const query = `
        SELECT
            d.id,
            d.camera_id,
            c.name AS camera_name,
            d.object_name,
            d.confidence,
            d.timestamp

        FROM detection_logs d

        LEFT JOIN cameras c
        ON d.camera_id = c.id

        ORDER BY d.timestamp DESC
    `;

    db.query(query, (err, results) => {

        if (err) {

            console.error(
                "Detection logs error:",
                err
            );

            return res.status(500).json({

                success: false,

                message:
                    "Failed to fetch detection logs"

            });
        }

        res.status(200).json({

            success: true,

            count: results.length,

            detections: results

        });

    });
};